### ISSUE TITLE
I cannot find intergron_Finder in bioconda

### ISSUE THREAD

**Issue by glichtenstein** [gem-pasteur/Integron_Finder#61] opened 2019-04-08 17:10 UTC
## Version of Integron_Finder:

Write here the output of integron_finder --version.

### OS

- [X ] Linux
- [ ] Windows
- [ ] Mac

## Expected behavior

Find and install integron_finder and its dependencies using bioconda

## Actual behavior

I cannot find any integron, nor integron_finder package in bioconda repositories

## Steps to reproduce behavior
```
conda search integron_finder
conda install integron_finder
```

## Relevant logs and/or screenshots

(Paste any relevant logs - please use code blocks (```) to format console output,
logs, and code as it's very hard to read otherwise.)

**Comment by bneron** [comment] 2019-04-19 09:30
as soon we will release the official 2.0 version

**Comment by FranckLejzerowicz** [comment] 2019-10-29 22:15
Hello.
Is the bioconda release available? Indeed, I have the same issue:

```
$ conda create -n integron_finder python=3.6
$ conda activate integron_finder
(integron_finder) $ conda config --add channels bioconda
Warning: 'bioconda' already in 'channels' list, moving to the top
(integron_finder) $ conda install integron_finder
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - integron_finder

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/ursky/linux-64
  - https://conda.anaconda.org/ursky/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Thanks for the tool I'm eager to use it.
Franck

**Comment by FranckLejzerowicz** [comment] 2019-11-01 18:41
I could work my way out with pip - thanks!

**Comment by jeanrjc** [comment] 2019-11-15 11:07
Duplicate of #57 #63 and #64

**Closed by jeanrjc** 2019-11-15 11:07 UTC
