### ISSUE TITLE
 Error related to prodigal: RuntimeError("{0} failed returncode = {1}".format(prodigal_cmd, returncode))

### ISSUE THREAD

**Issue by sasonbol** [gem-pasteur/Integron_Finder#79] opened 2020-10-04 22:09 UTC
Hello,
I used to work with intgeron finder version 2 on a virtual environment smoothly, but now I am always getting an error related to prodigal which I cannot resolve

## Version of Integron_Finder:

integron_finder version 2-2020-10-04
Using:    
 - Python 3.7.3 (default, Mar 27 2019, 22:11:17)  [GCC 7.3.0]
 - numpy 1.17.4
 - pandas 0.25.3
 - matplolib 3.1.1
 - biopython 1.75

### OS

- [ ] Linux (Ubuntu)

## Expected behavior
integron_finder was expected to run normally as I used it before with similar sequences with no errors. Now it is always generating this error

## Actual behavior
cannot process the replicon, getting an error:
 raise RuntimeError("{0} failed returncode = {1}".format(prodigal_cmd, returncode))

## Relevant logs and/or screenshots
Here is what I get exactly:

              INFO     :  ############ Processing replicon NZ_CP050695.1 (1/1) ############

Unknown option.

Usage:  prodigal [-a trans_file] [-c] [-d nuc_file] [-f output_type]
                 [-g tr_table] [-h] [-i input_file] [-m] [-n] [-o output_file]
                 [-p mode] [-q] [-s start_file] [-t training_file] [-v]

Do 'prodigal -h' for more information.

Traceback (most recent call last):
  File "/home/sarah/Integron_Finder/bin/integron_finder", line 11, in <module>
    load_entry_point('integron-finder', 'console_scripts', 'integron_finder')()

  File "/home/sarah/src/Integron_Finder/integron_finder/scripts/finder.py", line 601, in main
    integron_res, summary = find_integron_in_one_replicon(replicon, config)

  File "/home/sarah/src/Integron_Finder/integron_finder/scripts/finder.py", line 303, in find_integron_in_one_replicon
    protein_db = ProdigalDB(replicon, config)

  File "/home/sarah/src/Integron_Finder/integron_finder/prot_db.py", line 64, in __init__
    self._prot_file = self._make_protfile()

  File "/home/sarah/src/Integron_Finder/integron_finder/prot_db.py", line 403, in _make_protfile

    raise RuntimeError("{0} failed returncode = {1}".format(prodigal_cmd, returncode))

RuntimeError: /usr/bin/prodigal  -i /media/sarah/06422813422809CF/Updated PhD_work/hypersaline_environments_assemblies/Halophiles/arch-complete/Natrialbaceae_archeaon/Results_Integron_Finder_Natrialbaceae/tmp_NZ_CP050695.1/NZ_CP050695.1.fst -a /media/sarah/06422813422809CF/Updated PhD_work/hypersaline_environments_assemblies/Halophiles/arch-complete/Natrialbaceae_archeaon/Results_Integron_Finder_Natrialbaceae/tmp_NZ_CP050695.1/NZ_CP050695.1.prt -o /dev/null -q  failed returncode = 15

I would be grateful if you could help me out to solve this problem,
Best,
Sarah

**Comment by bneron** [comment] 2020-12-08 10:49
can you tell me which version of prodigal you run?

**Comment by nwalas** [comment] 2021-01-13 17:09
I am also receiving this error and I tried with both prodigal 2.6.3 and 2.6.2 (which I believe is the minimum for the program).

**Comment by bneron** [comment] 2021-01-14 09:45
can you run just prodigal on  your data without the -o option ?

**Comment by bneron** [comment] 2021-01-14 09:46
`prodigal -i /media/sarah/06422813422809CF/Updated PhD_work/hypersaline_environments_assemblies/Halophiles/arch-complete/Natrialbaceae_archeaon/Results_Integron_Finder_Natrialbaceae/tmp_NZ_CP050695.1/NZ_CP050695.1.fst -a /media/sarah/06422813422809CF/Updated PhD_work/hypersaline_environments_assemblies/Halophiles/arch-complete/Natrialbaceae_archeaon/Results_Integron_Finder_Natrialbaceae/tmp_NZ_CP050695.1/NZ_CP050695.1.prt`

**Comment by nwalas** [comment] 2021-01-14 16:50
Hi, when I run with any commands for prodigal like:

integron_finder test_assembled.fasta --local-max **prodigal -i users**/nikolinawalas/miniconda3/envs/integron_finder/bin/prodigal     
 
I am returned the error: unrecognized arguments: prodigal -i

Isn't integron_finder meant to manually command the attached databases?

Thanks!

**Comment by nwalas** [comment] 2021-01-14 17:17
I also tried just running prodigal -i (path to my fasta file) like you suggested and I get returned: 

Error: can't open input file /user/nikolinawalas/desktop/graham lab/cre/fasta/test_assembled.fasta.

**Comment by nwalas** [comment] 2021-01-26 22:49
Hi all; I have resolved this issue. 
For me, it seemed to be an issue with my fasta file. It had short read sequences, I needed to remove all ">seq" line breaks in my fasta file for integron finder to recognize it as one sequence. Hope this helps!

**Comment by sasonbol** [comment] 2021-03-03 08:37
Actually I cannot find protein file in the created temporary folder. I am only getting  a fasta file (.fst)

**Comment by sasonbol** [comment] 2021-03-03 08:39
I am using a complete circular genome so I don't really have short reads

**Comment by sasonbol** [comment] 2021-03-03 09:02
I am no using --prodigal command in my command line and I have used it before but I understand that it works by default

**Comment by sasonbol** [comment] 2021-03-04 10:00
The following command is not working as there is no prt file created. The tmp folder only has  a fasta file (.fst) at wihich this command can work on:
prodigal -i /media/sarah/06422813422809CF/Updated PhD_work/hypersaline_environments_assemblies/Halophiles/arch-complete/Natrialbaceae_archeaon/Results_Integron_Finder_Natrialbaceae/tmp_NZ_CP050695.1/NZ_CP050695.1.fst -a /media/sarah/06422813422809CF/Updated PhD_work/hypersaline_environments_assemblies/Halophiles/arch-complete/Natrialbaceae_archeaon/Results_Integron_Finder_Natrialbaceae/tmp_NZ_CP050695.1/NZ_CP050695.1.prt

**Comment by jeanrjc** [comment] 2021-03-04 11:10
Hello @sasonbol,

What is the output of the command you just showed ?

**Comment by sasonbol** [comment] 2021-03-04 12:07
Here is the output that I got:
PRODIGAL v2.6.3 [February, 2016]         
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.     
-------------------------------------

Error: can't open input file NZ_CP004393.1.prt.

**Comment by jeanrjc** [comment] 2021-03-04 12:38
The .prt should be the output file, not the input one. Can you make sure that the .fst is the input (-i) and the .prt the output (-a).
Can you show also all your terminal session when doing the following : 
```bash
cd "/media/sarah/06422813422809CF/Updated PhD_work/hypersaline_environments_assemblies/Halophiles/arch-complete/Natrialbaceae_archeaon/Results_Integron_Finder_Natrialbaceae/tmp_NZ_CP050695.1/"
ls -lh
prodigal -i NZ_CP050695.1.fst -a NZ_CP050695.1.prt
```

(make sure the path changing directory with `cd` is correct)

**Comment by sasonbol** [comment] 2021-03-04 12:51
OK. I tried on another sequence which showed the same problem, and a prt file was created when I used the prodigal command, but it is still not working when I use the integron_finder command.
I tried to run integron finder on the same sequence, but I got this error now:
command used: integron_finder celeribacter-chromosome.fasta --circ --local-max -dt 8000 --promoter-attI --pdf --gbk

                     =======================


INFO     :  ############ Processing replicon NZ_CP004393.1 (1/1) ############

INFO     :  Starting Default search ... :
Traceback (most recent call last):
  File "/home/sarah/Integron_Finder/bin/integron_finder", line 11, in <module>
    load_entry_point('integron-finder', 'console_scripts', 'integron_finder')()
  File "/home/sarah/src/Integron_Finder/integron_finder/scripts/finder.py", line 601, in main
    integron_res, summary = find_integron_in_one_replicon(replicon, config)
  File "/home/sarah/src/Integron_Finder/integron_finder/scripts/finder.py", line 321, in find_integron_in_one_replicon
    cpu=config.cpu)
  File "/home/sarah/src/Integron_Finder/integron_finder/infernal.py", line 129, in find_attc
    raise RuntimeError("{0} failed returncode = {1}".format(cmsearch_cmd, returncode))
RuntimeError: /home/sarah/miniconda3/bin/cmsearch --cpu 1 -A /media/sarah/06422813422809CF/Updated PhD_work/hypersaline_environments_assemblies/Halophiles/bacteria-complete/new-complete/Celeribacter-indicus/Results_Integron_Finder_celeribacter-chromosome/tmp_NZ_CP004393.1/NZ_CP004393.1_attc.res --tblout /media/sarah/06422813422809CF/Updated PhD_work/hypersaline_environments_assemblies/Halophiles/bacteria-complete/new-complete/Celeribacter-indicus/Results_Integron_Finder_celeribacter-chromosome/tmp_NZ_CP004393.1/NZ_CP004393.1_attc_table.res -E 10 --incE 1.0 /home/sarah/src/Integron_Finder/data/Models/attc_4.cm /media/sarah/06422813422809CF/Updated PhD_work/hypersaline_environments_assemblies/Halophiles/bacteria-complete/new-complete/Celeribacter-indicus/Results_Integron_Finder_celeribacter-chromosome/tmp_NZ_CP004393.1/NZ_CP004393.1.fst failed returncode = 1

**Comment by sasonbol** [comment] 2021-03-09 07:16
I uninstalled and reinstalled prodigal2.6.3, but the same problem still exists

**Comment by jeanrjc** [comment] 2021-04-21 16:32
Closing because not able to reproduce the problem. I'll reopen if more details are brought showing that there might be a bug in IntegronFinder.

**Closed by jeanrjc** 2021-04-21 16:32 UTC
