### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by vbrover** [gem-pasteur/Integron_Finder#64] opened 2019-11-13 21:00 UTC
### OS

- [ x] Linux
- [ ] Windows
- [ ] Mac

## Expected behavior

Write here.

## Actual behavior

Write here.

## Steps to reproduce behavior
```
$ conda config --add channels defaults
Warning: 'defaults' already in 'channels' list, moving to the top
(base) 
$ conda config --add channels defaults
Warning: 'defaults' already in 'channels' list, moving to the top
(base) 
$ conda config --add channels bioconda
Warning: 'bioconda' already in 'channels' list, moving to the top
(base) 
$ conda install integron_finder
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - integron_finder

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
Exit code 1

Or `pip`:
```
$ pip install integron_finder
Looking in indexes: https://artifactory.ncbi.nlm.nih.gov/artifactory/api/pypi/python-virtual-repo/simple
Collecting integron_finder
  Downloading https://artifactory.ncbi.nlm.nih.gov/artifactory/api/pypi/python-virtual-repo/packages/packages/cb/0a/3c91eb70d00006a40ebcdc3ed07074bad6f8b0baae36669cfa064f016a5d/integron_finder-1.5.1.tar.gz (4.5MB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 4.5MB 39.0MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/brovervv/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cfyli45g/integron-finder/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cfyli45g/integron-finder/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-cfyli45g/integron-finder/pip-egg-info
         cwd: /tmp/pip-install-cfyli45g/integron-finder/
    Complete output (1 lines):
    Sorry, Python 3 is not supported yet
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(base) 
```
Exit code = 1.

## Relevant logs and/or screenshots

(Paste any relevant logs - please use code blocks (```) to format console output,
logs, and code as it's very hard to read otherwise.)

**Comment by jfourquet2** [comment] 2019-11-15 10:44
Hi,
I use virtual env to install integron finder because I had also issues with conda an pip.
python3 -m venv Integron_Finder

source Integron_Finder/bin/activate

pip install git+https://github.com/gem-pasteur/Integron_Finder/#egg=integron_finder

integron_finder -h #test if it works

deactivate # deactivate environment

I hope it could help !

**Comment by jeanrjc** [comment] 2019-11-15 11:07
Duplicate of #57 and #63 
@jfourquet2's method is good as well.

**Closed by jeanrjc** 2019-11-15 11:07 UTC

**Comment by vbrover** [comment] 2019-11-18 16:16
Thank you!
