### ISSUE TITLE
Installing from pip not working

### ISSUE THREAD

**Issue by leaemiliepradier** [gem-pasteur/Integron_Finder#74] opened 2019-11-21 16:02 UTC
Hello, i'm unable to install integron_finder from pip following the directions in your README.md

## Version of Integron_Finder:

integron_finder-1.5.1

### OS

- [x] Linux
- [ ] Windows
- [ ] Mac

## Expected behavior

Showing an error or minimalistic help when executing the command 
`integron_finder` using a python2.7 environment

The installation with python 3.5 and 3.6 simply fails, as shown below. 
` pip install integron_finder`   

## Actual behavior

With a virtual environment running with python 3.6, the command `pip install integron_finder` yields:

```
    ERROR: Command errored out with exit status 1:
     command: /home/irene/envs/py36/bin/python3.5 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k5znen5k/integron-finder/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k5znen5k/integron-finder/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-k5znen5k/integron-finder/pip-egg-info
         cwd: /tmp/pip-install-k5znen5k/integron-finder/
    Complete output (1 lines):
    Sorry, Python 3 is not supported yet
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

With a virtual environment running with python2.7, the previous command works. But `integron_finder` yields:
```
Traceback (most recent call last):
  File "/home/irene/envs/py27/bin/integron_finder", line 1403, in <module>
    or define INTEGRON_HOME environment variable.""")
Exception: cannot find integron_finder data check your installation
or define INTEGRON_HOME environment variable.
```

The command `integron_finder -h` yields the same.

**Comment by jeanrjc** [comment] 2019-11-21 16:27
Duplicate of #57 #63 #64

**Closed by jeanrjc** 2019-11-21 16:27 UTC

**Comment by leaemiliepradier** [comment] 2019-11-21 16:44
Don't you want to add that to the README.md ?
This is the one that worked in a py 3.6 environment
`pip install git+https://github.com/gem-pasteur/Integron_Finder/#egg=integron_finder`

**Comment by jeanrjc** [comment] 2019-11-21 17:24
You're right, it's done. Thanks.
